# Generated by Django 4.1 on 2024-09-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_task_assignees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['last_name', 'first_name', 'position'], 'verbose_name_plural': 'Workers'},
        ),
    ]
