# Generated by Django 4.1 on 2024-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
