# Generated by Django 4.1 on 2024-09-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_task_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='responsible',
        ),
    ]
