# Generated by Django 4.1 on 2024-09-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0010_worker_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='gender',
        ),
    ]
