# Generated by Django 4.1 on 2024-09-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0011_remove_worker_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
